image: hashicorp/terraform:latest

stages:
  - setup
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - apk add --no-cache nodejs npm
  - npm install

setup:
  stage: setup
  tags:
    - my-runner-tag
  script:
    - echo "Setting up Terraform and Node.js dependencies"

deploy:
  stage: deploy
  tags:
    - test
  script:
    - echo "Starting Terraform deployment"
    - pwd
    - ls -l
    - cd terraform
    - terraform init
    - terraform apply -auto-approve
    - cd ..
    - echo "Current directory after Terraform:"
    - pwd
    - ls -l
    - echo "Terraform deployment complete"
    - echo "Deploying Node.js application"
    - node hello.js
  artifacts:
    paths:
      - terraform/main.tf
      - terraform/variables.tf
      - terraform/outputs.tf
    expire_in: 1 week

after_script:
  - echo "Cleaning up"
  - rm -rf terraform/*.tf
