image: hashicorp/terraform:latest

stages:
  - setup
  - deploy

variables:
  NODE_ENV: production

cache:
  paths:
    - node_modules/

before_script:
  - apk add --no-cache nodejs npm
  - npm install

setup:
  stage: setup
  tags:
    - test
  script:
    - echo "Setting up Terraform and Node.js dependencies"
    - node -v
    - npm -v

deploy:
  stage: deploy
  tags:
    - test
  script:
    - echo "Starting Terraform deployment"
    - pwd
    - ls -l
    - cd provisioners/vm
    - ls -l
    - terraform init
    - terraform apply -auto-approve
    - cd ../..
    - echo "Current directory after Terraform:"
    - pwd
    - ls -l
    - echo "Terraform deployment complete"
    - echo "Deploying Node.js application"
    - node hello.js
  artifacts:
    paths:
      - provisioners/vm/main.tf
      - provisioners/vm/variables.tf
      - provisioners/vm/outputs.tf
    expire_in: 1 week

after_script:
  - echo "Cleaning up"
  - ls -l provisioners/vm
  - rm -rf provisioners/vm/*.tf
