image: hashicorp/terraform:latest

stages:
  - init
  - plan
  - apply

before_script:
  - terraform --version
  - terraform init -backend-config="path=$TF_ROOT/terraform.tfstate"

init:
  stage: init
  script:
    - terraform init

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  when: manual
  dependencies:
    - plan
