image: hashicorp/terraform:latest

stages:
  - setup
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - apk add --no-cache nodejs npm
  - npm install

setup:
  stage: setup
  script:
    - echo "Setting up Terraform and Node.js dependencies"

deploy:
  stage: deploy
  script:
    - echo "Starting Terraform deployment"
    - cd terraform
    - terraform init
    - terraform apply -auto-approve
    - echo "Terraform deployment complete"
    - cd ..
    - echo "Deploying Node.js application"
    - node hello.js
  artifacts:
    paths:
      - terraform/main.tf
      - terraform/variables.tf
      - terraform/outputs.tf
    expire_in: 1 week

after_script:
  - echo "Cleaning up"
  - rm -rf terraform/*.tf
