image: alpine:latest

stages:
  - test

test:
  stage: test
  script:
    - echo "Running tests..."
    - # Add your test commands here
  after_script:
    - echo "Cleaning up..."
    - # Add your cleanup commands here
