name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}

      - name: SSH into VM and install software
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_EXTERNAL_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            # Install Node.js
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # Create a directory for the application
            mkdir -p ~/hello-world-app
            cd ~/hello-world-app

            # Create package.json
            echo '{
              "name": "hello-world-app",
              "version": "1.0.0",
              "main": "index.js",
              "dependencies": {
                "express": "^4.17.1"
              },
              "scripts": {
                "start": "node index.js"
              }
            }' > package.json

            # Install dependencies
            npm install

            # Create the application
            echo 'const express = require("express");
            const app = express();
            const port = 3000;

            app.get("/", (req, res) => {
              res.send("Hello World!");
            });

            app.listen(port, () => {
              console.log(`Hello world app listening at http://localhost:${port}`);
            });' > index.js

            # Start the application
            npm start &

            # Ensure the application starts on boot
            sudo bash -c 'cat << EOF > /etc/systemd/system/hello-world-app.service
            [Unit]
            Description=Hello World Node.js App

            [Service]
            ExecStart=/usr/bin/npm start
            WorkingDirectory=/home/YOUR_USERNAME/hello-world-app
            Restart=always
            User=YOUR_USERNAME

            [Install]
            WantedBy=multi-user.target
            EOF'

            sudo systemctl daemon-reload
            sudo systemctl start hello-world-app
            sudo systemctl enable hello-world-app
